version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: dbApp
      MYSQL_USER: dbTest
      MYSQL_PASSWORD: dbTest
      MYSQL_ROOT_PASSWORD: dbTest
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-pdbTest"]
      interval: 5s
      retries: 10
    networks:
      - app-network


  server:
    build: .
    container_name: spring-app
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/dbApp
      SPRING_DATASOURCE_USERNAME: dbTest
      SPRING_DATASOURCE_PASSWORD: dbTest
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
